heat_template_version: 2013-05-23

description: >
  Create network, subnet, port, and boot a vm from a volume, assign
  the port to the vm.

parameters:


resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: heat-net1

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 192.168.19.0/24

  server1:
    type: OS::Nova::Server
    properties:
      name: Server1_original_ksc_zq
      block_device_mapping_v2:
        - delete_on_termination: True
          boot_index: 0
          volume_id: 9235c1e7-6da4-4d26-ae0f-283e2db502c2
      flavor: 6
      networks:
        - port: { get_resource: server1_port }

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }


outputs:
  server1_private_ip:
    description: IP address of server1 in private network
    value: { get_attr: [ server1, first_address ] }

