heat_template_version: 2013-05-23

description: >
  Create a security group with several security group rules

parameters:

resources:
  security_group:
      type: OS::Neutron::SecurityGroup
      properties:
        name: web_server_security_group
        rules:
          - protocol: icmp
            port_range_min: 0
            port_range_max: 255
            ethertype: IPv4
          - protocol: tcp
            port_range_min: 443
            port_range_max: 443
          - protocol: tcp
            port_range_min: 80
            port_range_max: 80

outputs:

